version: "3"
services:
  epitech_time_clock_server:
    container_name: epitech_time_clock_server
    build: ./server
    ports:
      - 1234:1234
    volumes:
      - ./server:/usr/server
  epitech_time_clock_client:
    container_name: epitech_time_clock_client
    build: ./client
    ports:
      - 1235:1235
    volumes:
      - ./client:/usr/client
    links:
      - epitech_time_clock_server